### PR TITLE
Eggd arrays

### PR DESCRIPTION
**Pull request by Yu-jinKim**
This change is [Reviewable](https://reviewable.io/reviews/eastgenomics/opencga_data_upload/2)

### CODE REVIEW

**Review by jethror1 — CHANGES_REQUESTED** [review]
> Reviewed 2 of 6 files at r1.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/opencga_data_upload/2)* status: 2 of 6 files reviewed, 9 unresolved discussions (waiting on @Yu-jinKim)

___
*[`dxapp.json` line 9 at r1](https://reviewable.io/reviews/eastgenomics/opencga_data_upload/2#-NICen9M4NInRqzqkaXL:-NICen9M4NInRqzqkaXM:bb7qbb3) ([raw file](https://github.com/eastgenomics/opencga_data_upload/blob/5b26c1543349650b05a32a12e32890e635aaa5ea/dxapp.json#L9)):*
> ```JSON
>   "inputSpec": [
>     {
>       "name": "input_vcf",
> ```

vcfs



_Code quote:_
```JSON
input_vcf
```
___
*[`resources/home/dnanexus/opencga_upload_and_index.py` line 60 at r1](https://reviewable.io/reviews/eastgenomics/opencga_data_upload/2#-NICgDlYB4dvRK4QC6_s:-NICgDlZ7cjdx4oHE6Te:bytvqs8) ([raw file](https://github.com/eastgenomics/opencga_data_upload/blob/5b26c1543349650b05a32a12e32890e635aaa5ea/resources/home/dnanexus/opencga_upload_and_index.py#L60)):*
> ```Python
>         full_name = file.split(".")[0]
>         # look for the vcf files that have the name in them
>         vcfs = [i for i in vcf_files if full_name in i]
> ```

this could just be directly in the list comp:
```
data.extend([[vcf, file] for vcf in vcf_files if full_name in vcf])
```



_Code quote:_
```Python
        vcfs = [i for i in vcf_files if full_name in i]

        for vcf in vcfs:
            data.append([vcf, file])
```
___
*[`resources/home/dnanexus/opencga_upload_and_index.py` line 73 at r1](https://reviewable.io/reviews/eastgenomics/opencga_data_upload/2#-NICgURKAsdde1ge48Pd:-NICgURKAsdde1ge48Pe:ble9lst) ([raw file](https://github.com/eastgenomics/opencga_data_upload/blob/5b26c1543349650b05a32a12e32890e635aaa5ea/resources/home/dnanexus/opencga_upload_and_index.py#L73)):*
> ```Python
>     parser.add_argument('--project', help='OpenCGA Project where the file will be loaded')
>     parser.add_argument('--study', help='OpenCGA Study where the file will be loaded')
>     parser.add_argument('--metadata', nargs="+", help='Zip file containing the metadata (minimum required information: "study")')
> ```

file(s)



_Code quote:_
```Python
file
```
___
*[`resources/home/dnanexus/opencga_upload_and_index.py` line 77 at r1](https://reviewable.io/reviews/eastgenomics/opencga_data_upload/2#-NICgWPc925ukVQ58-fA:-NICgWPc925ukVQ58-fB:ble9lst) ([raw file](https://github.com/eastgenomics/opencga_data_upload/blob/5b26c1543349650b05a32a12e32890e635aaa5ea/resources/home/dnanexus/opencga_upload_and_index.py#L77)):*
> ```Python
>     parser.add_argument('--cli', help='Path to OpenCGA cli')
>     # parser.add_argument('--cli21', help='Path to OpenCGA cli 2.1')
>     parser.add_argument('--vcf', nargs="+", help='Input vcf file')
> ```

file(s)



_Code quote:_
```Python
file
```
___
*[`resources/home/dnanexus/opencga_upload_and_index.py` line 130 at r1](https://reviewable.io/reviews/eastgenomics/opencga_data_upload/2#-NICjOTT9hco9XjeMptB:-NICjOTT9hco9XjeMptC:b-hjz78j) ([raw file](https://github.com/eastgenomics/opencga_data_upload/blob/5b26c1543349650b05a32a12e32890e635aaa5ea/resources/home/dnanexus/opencga_upload_and_index.py#L130)):*
> ```Python
> 
>     # Read metadata file
>     if metadata:
> ```

are you just not handling no metadata?
___
*[`resources/home/dnanexus/opencga_upload_and_index.py` line 194 at r1](https://reviewable.io/reviews/eastgenomics/opencga_data_upload/2#-NICj_mGAnQy0hMpqzLI:-NICj_mGAnQy0hMpqzLJ:bdvy3k8) ([raw file](https://github.com/eastgenomics/opencga_data_upload/blob/5b26c1543349650b05a32a12e32890e635aaa5ea/resources/home/dnanexus/opencga_upload_and_index.py#L194)):*
> ```Python
> 
>             # Launch variant stats index
>             logger.info("Launching variant stats...")
> ```

isn't the idea that you do this after uploading all vcfs so we just launch one annotation job? 

we can still set a bool at the to to check at least one vcf is not annotated, and then know to trigger an annotation and subsequent indexing job.

also not sure if the first index is needed after upload per vcf or can be done once when all vcfs are uploaded - need to check with marta.

another thing you could do is build a dict of all vcfs and the status returned from `check_file_status()` with one entry per vcf all all returned objects, then you can check all `annotated` are true or not



_Code quote:_
```Python
            # Launch variant stats index
            logger.info("Launching variant stats...")
            vsi_job = variant_stats_index(oc=oc, study=study_fqn, cohort='ALL', logger=logger)
            # TODO: Check status of this job at the end

            # ANNOTATION
            if annotated:
                logger.info("File {} is already annotated in the OpenCGA study {}.".format(os.path.basename(vcf_file),
                                                                                        study_fqn))
            else:
                logger.info("Annotating file {} into study {}...".format(os.path.basename(vcf_file), study_fqn))
                annotate_variants(oc=oc, project=project, study=study, logger=logger, delay=delay)
```
___
*[`src/opencga-data-upload.sh` line 58 at r1](https://reviewable.io/reviews/eastgenomics/opencga_data_upload/2#-NIChpooDdvC3cnrvy0k:-NIChpooDdvC3cnrvy0l:b-zadje) ([raw file](https://github.com/eastgenomics/opencga_data_upload/blob/5b26c1543349650b05a32a12e32890e635aaa5ea/src/opencga-data-upload.sh#L58)):*
> ```Shell
>     # Install python dependencies
>     echo "Installing requirements"
>     pip install pyopencga-2.4.9-py3-none-any.whl
> ```

does this not have other dependencies or is it all std lib?
___
*[`src/opencga-data-upload.sh` line 62 at r1](https://reviewable.io/reviews/eastgenomics/opencga_data_upload/2#-NICi-kA5V3kk8Wr0WnV:-NICi-kA5V3kk8Wr0WnW:b7i5vwx) ([raw file](https://github.com/eastgenomics/opencga_data_upload/blob/5b26c1543349650b05a32a12e32890e635aaa5ea/src/opencga-data-upload.sh#L62)):*
> ```Shell
>     vcf_string=""
>     # Gather all vcfs for passing to the python script and build string to pass
>     for vcf in $(ls ~/in/input_vcf/); do
> ```

should use find over ls for gathering files and can just be `vcf_string=$(find ~/in/input_vcf/ -type f)`

example:
```
$ files=$(find resources/ -type f | head -n5)
$ echo $files
resources/usr/local/bin/mark-success resources/usr/local/bin/jq-linux64 resources/usr/local/bin/mark-section resources/home/dnanexus/packages/numpy-1.22.2-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl resources/home/dnanexus/packages/filetype-1.1.0-py2.py3-none-any.whl
```



_Code quote:_
```Shell
ls ~/in/input_vcf/
```
___
*[`src/opencga-data-upload.sh` line 76 at r1](https://reviewable.io/reviews/eastgenomics/opencga_data_upload/2#-NICinPj50IGP_1YHwb2:-NICinPj50IGP_1YHwb3:bnj7hl0) ([raw file](https://github.com/eastgenomics/opencga_data_upload/blob/5b26c1543349650b05a32a12e32890e635aaa5ea/src/opencga-data-upload.sh#L76)):*
> ```Shell
>       metadata_string+=" --metadata"
> 
>       for metadata in $(ls ~/in/input_metadata/); do
> ```

same as above



_Code quote:_
```Shell
      for metadata in $(ls ~/in/input_metadata/); do
        metadata_string+=" ~/in/input_metadata/${metadata}"
      done
```

**Review by Yu-jinKim — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/opencga_data_upload/2)* status: 2 of 6 files reviewed, 9 unresolved discussions (waiting on @jethror1)

___
*[`dxapp.json` line 9 at r1](https://reviewable.io/reviews/eastgenomics/opencga_data_upload/2#-NICen9M4NInRqzqkaXL:-NICtbOW2dAiiJIj_ga4:b-896fix) ([raw file](https://github.com/eastgenomics/opencga_data_upload/blob/5b26c1543349650b05a32a12e32890e635aaa5ea/dxapp.json#L9)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

vcfs
</blockquote></details>

Done.
___
*[`resources/home/dnanexus/opencga_upload_and_index.py` line 60 at r1](https://reviewable.io/reviews/eastgenomics/opencga_data_upload/2#-NICgDlYB4dvRK4QC6_s:-NICtyek-e32WCl12m7w:b-896fix) ([raw file](https://github.com/eastgenomics/opencga_data_upload/blob/5b26c1543349650b05a32a12e32890e635aaa5ea/resources/home/dnanexus/opencga_upload_and_index.py#L60)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

this could just be directly in the list comp:
```
data.extend([[vcf, file] for vcf in vcf_files if full_name in vcf])
```
</blockquote></details>

Done.
___
*[`src/opencga-data-upload.sh` line 58 at r1](https://reviewable.io/reviews/eastgenomics/opencga_data_upload/2#-NIChpooDdvC3cnrvy0k:-NICrcpY5TXXkxVN7-93:b-wencxv) ([raw file](https://github.com/eastgenomics/opencga_data_upload/blob/5b26c1543349650b05a32a12e32890e635aaa5ea/src/opencga-data-upload.sh#L58)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

does this not have other dependencies or is it all std lib?
</blockquote></details>

the requirement file only had that
___
*[`src/opencga-data-upload.sh` line 62 at r1](https://reviewable.io/reviews/eastgenomics/opencga_data_upload/2#-NICi-kA5V3kk8Wr0WnV:-NICsmE23m2jvW0kuOrI:b-896fix) ([raw file](https://github.com/eastgenomics/opencga_data_upload/blob/5b26c1543349650b05a32a12e32890e635aaa5ea/src/opencga-data-upload.sh#L62)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

should use find over ls for gathering files and can just be `vcf_string=$(find ~/in/input_vcf/ -type f)`

example:
```
$ files=$(find resources/ -type f | head -n5)
$ echo $files
resources/usr/local/bin/mark-success resources/usr/local/bin/jq-linux64 resources/usr/local/bin/mark-section resources/home/dnanexus/packages/numpy-1.22.2-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl resources/home/dnanexus/packages/filetype-1.1.0-py2.py3-none-any.whl
```
</blockquote></details>

Done.
___
*[`src/opencga-data-upload.sh` line 76 at r1](https://reviewable.io/reviews/eastgenomics/opencga_data_upload/2#-NICinPj50IGP_1YHwb2:-NICsmaO7rkG7_u-JYoN:b-896fix) ([raw file](https://github.com/eastgenomics/opencga_data_upload/blob/5b26c1543349650b05a32a12e32890e635aaa5ea/src/opencga-data-upload.sh#L76)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

same as above
</blockquote></details>

Done.

**Review by Yu-jinKim — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/opencga_data_upload/2)* status: 2 of 6 files reviewed, 9 unresolved discussions (waiting on @jethror1)

___
*[`resources/home/dnanexus/opencga_upload_and_index.py` line 73 at r1](https://reviewable.io/reviews/eastgenomics/opencga_data_upload/2#-NICgURKAsdde1ge48Pd:-NICzI_21QQ9xW-sm38K:b-896fix) ([raw file](https://github.com/eastgenomics/opencga_data_upload/blob/5b26c1543349650b05a32a12e32890e635aaa5ea/resources/home/dnanexus/opencga_upload_and_index.py#L73)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

file(s)
</blockquote></details>

Done.
___
*[`resources/home/dnanexus/opencga_upload_and_index.py` line 77 at r1](https://reviewable.io/reviews/eastgenomics/opencga_data_upload/2#-NICgWPc925ukVQ58-fA:-NICzI8431sB_ssUa9MO:b-896fix) ([raw file](https://github.com/eastgenomics/opencga_data_upload/blob/5b26c1543349650b05a32a12e32890e635aaa5ea/resources/home/dnanexus/opencga_upload_and_index.py#L77)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

file(s)
</blockquote></details>

Done.
___
*[`resources/home/dnanexus/opencga_upload_and_index.py` line 130 at r1](https://reviewable.io/reviews/eastgenomics/opencga_data_upload/2#-NICjOTT9hco9XjeMptB:-NICymoU9DHXrXcb2EN2:b1h126) ([raw file](https://github.com/eastgenomics/opencga_data_upload/blob/5b26c1543349650b05a32a12e32890e635aaa5ea/resources/home/dnanexus/opencga_upload_and_index.py#L130)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

are you just not handling no metadata?
</blockquote></details>

not handling metadata sounds painful and probably requires some functions and thinking so if i can get the metadata bit done, it'll be easier to do the no metadata bit afterwards aka selective procrastination

**Review by jethror1 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/opencga_data_upload/2)* status: 2 of 6 files reviewed, 4 unresolved discussions (waiting on @Yu-jinKim)

___
*[`resources/home/dnanexus/opencga_upload_and_index.py` line 130 at r1](https://reviewable.io/reviews/eastgenomics/opencga_data_upload/2#-NICjOTT9hco9XjeMptB:-NID-lDS0E8jHVLSvXIJ:b-8ul1in) ([raw file](https://github.com/eastgenomics/opencga_data_upload/blob/5b26c1543349650b05a32a12e32890e635aaa5ea/resources/home/dnanexus/opencga_upload_and_index.py#L130)):*
<details><summary><i>Previously, Yu-jinKim wrote…</i></summary><blockquote>

not handling metadata sounds painful and probably requires some functions and thinking so if i can get the metadata bit done, it'll be easier to do the no metadata bit afterwards aka selective procrastination
</blockquote></details>

I approve
___
*[`src/opencga-data-upload.sh` line 58 at r1](https://reviewable.io/reviews/eastgenomics/opencga_data_upload/2#-NIChpooDdvC3cnrvy0k:-NID0w_7Enu2hD0YU1W-:b-wlg705) ([raw file](https://github.com/eastgenomics/opencga_data_upload/blob/5b26c1543349650b05a32a12e32890e635aaa5ea/src/opencga-data-upload.sh#L58)):*
<details><summary><i>Previously, Yu-jinKim wrote…</i></summary><blockquote>

the requirement file only had that
</blockquote></details>

```
$ johnnydep pyopencga==2.4.9
2022-12-01 14:11:53 [info     ] init johnnydist                [johnnydep.lib] dist=pyopencga==2.4.9 parent=None
2022-12-01 14:11:55 [info     ] init johnnydist                [johnnydep.lib] dist=pandas>=1.1.5 parent=pyopencga==2.4.9
2022-12-01 14:12:00 [info     ] init johnnydist                [johnnydep.lib] dist=pathlib>=1.0.1 parent=pyopencga==2.4.9
2022-12-01 14:12:02 [info     ] init johnnydist                [johnnydep.lib] dist=pip>=7.1.2 parent=pyopencga==2.4.9
2022-12-01 14:12:04 [info     ] init johnnydist                [johnnydep.lib] dist=pyyaml>=3.12 parent=pyopencga==2.4.9
2022-12-01 14:12:06 [info     ] init johnnydist                [johnnydep.lib] dist=requests>=2.7 parent=pyopencga==2.4.9
2022-12-01 14:12:07 [info     ] init johnnydist                [johnnydep.lib] dist=numpy>=1.20.3 parent=pandas>=1.1.5
2022-12-01 14:12:13 [info     ] init johnnydist                [johnnydep.lib] dist=python-dateutil>=2.8.1 parent=pandas>=1.1.5
2022-12-01 14:12:15 [info     ] init johnnydist                [johnnydep.lib] dist=pytz>=2020.1 parent=pandas>=1.1.5
2022-12-01 14:12:16 [info     ] init johnnydist                [johnnydep.lib] dist=six>=1.5 parent=python-dateutil>=2.8.1
2022-12-01 14:12:18 [info     ] init johnnydist                [johnnydep.lib] dist=certifi>=2017.4.17 parent=requests>=2.7
2022-12-01 14:12:19 [info     ] init johnnydist                [johnnydep.lib] dist=charset-normalizer<3,>=2 parent=requests>=2.7
2022-12-01 14:12:20 [info     ] init johnnydist                [johnnydep.lib] dist=idna<4,>=2.5 parent=requests>=2.7
2022-12-01 14:12:22 [info     ] init johnnydist                [johnnydep.lib] dist=urllib3<1.27,>=1.21.1 parent=requests>=2.7
name                              summary
--------------------------------  -------------------------------------------------------------------------------------------------------
pyopencga==2.4.9                  A REST client for OpenCGA REST web services
├── pandas>=1.1.5                 Powerful data structures for data analysis, time series, and statistics
│   ├── numpy>=1.20.3             NumPy is the fundamental package for array computing with Python.
│   ├── python-dateutil>=2.8.1    Extensions to the standard Python datetime module
│   │   └── six>=1.5              Python 2 and 3 compatibility utilities
│   └── pytz>=2020.1              World timezone definitions, modern and historical
├── pathlib>=1.0.1                Object-oriented filesystem paths
├── pip>=7.1.2                    The PyPA recommended tool for installing Python packages.
├── pyyaml>=3.12                  YAML parser and emitter for Python
└── requests>=2.7                 Python HTTP for Humans.
    ├── certifi>=2017.4.17        Python package for providing Mozilla's CA Bundle.
    ├── charset-normalizer<3,>=2  The Real First Universal Charset Detector. Open, modern and actively maintained alternative to Chardet.
    ├── idna<4,>=2.5              Internationalized Domain Names in Applications (IDNA)
    └── urllib3<1.27,>=1.21.1     HTTP library with thread-safe connection pooling, file post, and more.
```

I assume if you look at the job logs (that you haven't got as you haven't run it) it would be pip installing those from pypi too.

If you do `pip download -d resources/home/dnanexus/packages pyopencga==2.4.9` that should download it with all dependencies (assuming you're using python3.8 like in the app env), then you can install in the app with `sudo -H python3 -m pip install --no-index --no-deps packages/*`
___
*[`src/opencga-data-upload.sh` line 62 at r2](https://reviewable.io/reviews/eastgenomics/opencga_data_upload/2#-NID23cr7Z1zhtjli9Dj:-NID23cr7Z1zhtjli9Dk:bz9zl6b) ([raw file](https://github.com/eastgenomics/opencga_data_upload/blob/5daa6a7da2d33ea4a3ada84613a6f2fd910fed43/src/opencga-data-upload.sh#L62)):*
> ```Shell
>     if [ -n "${input_metadata}" ]; then
>       # Gather metadata files and build string to pass
>       metadata_string+=" --metadata "
> ```

should this not be `metadata_string=" --metadata "` and then `+=` for the metadata_string for the output of find below?



_Code quote:_
```Shell
metadata_string+=" --metadata "
```

**Review by Yu-jinKim — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/opencga_data_upload/2)* status: 1 of 19 files reviewed, 3 unresolved discussions (waiting on @jethror1)

___
*[`src/opencga-data-upload.sh` line 58 at r1](https://reviewable.io/reviews/eastgenomics/opencga_data_upload/2#-NIChpooDdvC3cnrvy0k:-NID8b6ZEaHVVfa3mkwt:b-896fix) ([raw file](https://github.com/eastgenomics/opencga_data_upload/blob/5b26c1543349650b05a32a12e32890e635aaa5ea/src/opencga-data-upload.sh#L58)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

```
$ johnnydep pyopencga==2.4.9
2022-12-01 14:11:53 [info     ] init johnnydist                [johnnydep.lib] dist=pyopencga==2.4.9 parent=None
2022-12-01 14:11:55 [info     ] init johnnydist                [johnnydep.lib] dist=pandas>=1.1.5 parent=pyopencga==2.4.9
2022-12-01 14:12:00 [info     ] init johnnydist                [johnnydep.lib] dist=pathlib>=1.0.1 parent=pyopencga==2.4.9
2022-12-01 14:12:02 [info     ] init johnnydist                [johnnydep.lib] dist=pip>=7.1.2 parent=pyopencga==2.4.9
2022-12-01 14:12:04 [info     ] init johnnydist                [johnnydep.lib] dist=pyyaml>=3.12 parent=pyopencga==2.4.9
2022-12-01 14:12:06 [info     ] init johnnydist                [johnnydep.lib] dist=requests>=2.7 parent=pyopencga==2.4.9
2022-12-01 14:12:07 [info     ] init johnnydist                [johnnydep.lib] dist=numpy>=1.20.3 parent=pandas>=1.1.5
2022-12-01 14:12:13 [info     ] init johnnydist                [johnnydep.lib] dist=python-dateutil>=2.8.1 parent=pandas>=1.1.5
2022-12-01 14:12:15 [info     ] init johnnydist                [johnnydep.lib] dist=pytz>=2020.1 parent=pandas>=1.1.5
2022-12-01 14:12:16 [info     ] init johnnydist                [johnnydep.lib] dist=six>=1.5 parent=python-dateutil>=2.8.1
2022-12-01 14:12:18 [info     ] init johnnydist                [johnnydep.lib] dist=certifi>=2017.4.17 parent=requests>=2.7
2022-12-01 14:12:19 [info     ] init johnnydist                [johnnydep.lib] dist=charset-normalizer<3,>=2 parent=requests>=2.7
2022-12-01 14:12:20 [info     ] init johnnydist                [johnnydep.lib] dist=idna<4,>=2.5 parent=requests>=2.7
2022-12-01 14:12:22 [info     ] init johnnydist                [johnnydep.lib] dist=urllib3<1.27,>=1.21.1 parent=requests>=2.7
name                              summary
--------------------------------  -------------------------------------------------------------------------------------------------------
pyopencga==2.4.9                  A REST client for OpenCGA REST web services
├── pandas>=1.1.5                 Powerful data structures for data analysis, time series, and statistics
│   ├── numpy>=1.20.3             NumPy is the fundamental package for array computing with Python.
│   ├── python-dateutil>=2.8.1    Extensions to the standard Python datetime module
│   │   └── six>=1.5              Python 2 and 3 compatibility utilities
│   └── pytz>=2020.1              World timezone definitions, modern and historical
├── pathlib>=1.0.1                Object-oriented filesystem paths
├── pip>=7.1.2                    The PyPA recommended tool for installing Python packages.
├── pyyaml>=3.12                  YAML parser and emitter for Python
└── requests>=2.7                 Python HTTP for Humans.
    ├── certifi>=2017.4.17        Python package for providing Mozilla's CA Bundle.
    ├── charset-normalizer<3,>=2  The Real First Universal Charset Detector. Open, modern and actively maintained alternative to Chardet.
    ├── idna<4,>=2.5              Internationalized Domain Names in Applications (IDNA)
    └── urllib3<1.27,>=1.21.1     HTTP library with thread-safe connection pooling, file post, and more.
```

I assume if you look at the job logs (that you haven't got as you haven't run it) it would be pip installing those from pypi too.

If you do `pip download -d resources/home/dnanexus/packages pyopencga==2.4.9` that should download it with all dependencies (assuming you're using python3.8 like in the app env), then you can install in the app with `sudo -H python3 -m pip install --no-index --no-deps packages/*`
</blockquote></details>

Done.
___
*[`src/opencga-data-upload.sh` line 62 at r2](https://reviewable.io/reviews/eastgenomics/opencga_data_upload/2#-NID23cr7Z1zhtjli9Dj:-NID8qeu-QXW7b6Cxazv:b-896fix) ([raw file](https://github.com/eastgenomics/opencga_data_upload/blob/5daa6a7da2d33ea4a3ada84613a6f2fd910fed43/src/opencga-data-upload.sh#L62)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

should this not be `metadata_string=" --metadata "` and then `+=` for the metadata_string for the output of find below?
</blockquote></details>

Done.

**Review by Yu-jinKim — COMMENTED** [review]
If you can find me a better solution to give the dnanexus file id to their json, i'll gladly take it

> *[Reviewable](https://reviewable.io/reviews/eastgenomics/opencga_data_upload/2#-:-NIDXES16GfV2OLCgjW9:bhnfi1a)* status: 1 of 26 files reviewed, 3 unresolved discussions (waiting on @jethror1)

___
*[`resources/home/dnanexus/opencga_upload_and_index.py` line 194 at r1](https://reviewable.io/reviews/eastgenomics/opencga_data_upload/2#-NICj_mGAnQy0hMpqzLI:-NIDXRNL7uV4bujhllvs:b-wq4tl2) ([raw file](https://github.com/eastgenomics/opencga_data_upload/blob/5b26c1543349650b05a32a12e32890e635aaa5ea/resources/home/dnanexus/opencga_upload_and_index.py#L194)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

isn't the idea that you do this after uploading all vcfs so we just launch one annotation job? 

we can still set a bool at the to to check at least one vcf is not annotated, and then know to trigger an annotation and subsequent indexing job.

also not sure if the first index is needed after upload per vcf or can be done once when all vcfs are uploaded - need to check with marta.

another thing you could do is build a dict of all vcfs and the status returned from `check_file_status()` with one entry per vcf all all returned objects, then you can check all `annotated` are true or not
</blockquote></details>

kinda done

**Review by jethror1 — CHANGES_REQUESTED** [review]
have done below

> *[Reviewable](https://reviewable.io/reviews/eastgenomics/opencga_data_upload/2#-:-NIHNkpvCYMG-2A0s5Uy:bzcu2hy)* status: 1 of 26 files reviewed, 6 unresolved discussions (waiting on @Yu-jinKim)

___
*[`dxapp.json` line 18 at r4](https://reviewable.io/reviews/eastgenomics/opencga_data_upload/2#-NIHGyJQEWZhK5k2VLuQ:-NIHGyJR4PBcu1Kg8v1Q:b-7qlapa) ([raw file](https://github.com/eastgenomics/opencga_data_upload/blob/ce3f000c5a275fee55cbd9ca2626acca3ce0760b/dxapp.json#L18)):*
> ```JSON
>     {
>       "name": "input_metadata",
>       "label": "Metadata file",
> ```

files



_Code quote:_
```JSON
file
```
___
*[`resources/home/dnanexus/opencga_upload_and_index.py` line 96 at r4](https://reviewable.io/reviews/eastgenomics/opencga_data_upload/2#-NIHH32Z72NOTCrvlzHB:-NIHH32Z72NOTCrvlzHC:bxe8tt9) ([raw file](https://github.com/eastgenomics/opencga_data_upload/blob/ce3f000c5a275fee55cbd9ca2626acca3ce0760b/resources/home/dnanexus/opencga_upload_and_index.py#L96)):*
> ```Python
>     vcf_data = {}
> 
>     if args.metadata is not None:
> ```

this can just be `if args.metadata:`



_Code quote:_
```Python
if args.metadata is not None:
```
___
*[`resources/home/dnanexus/opencga_upload_and_index.py` line 161 at r4](https://reviewable.io/reviews/eastgenomics/opencga_data_upload/2#-NIHLgcJ3Tl_vsi5GG5D:-NIHLgcJ3Tl_vsi5GG5E:b-4e46f4) ([raw file](https://github.com/eastgenomics/opencga_data_upload/blob/ce3f000c5a275fee55cbd9ca2626acca3ce0760b/resources/home/dnanexus/opencga_upload_and_index.py#L161)):*
> ```Python
>         study_fqn = vcf_data[vcf]["study_fqn"]
>         multi_file = vcf_data[vcf]["multi_file"]
>         # find dnanexus id
> ```

the file ID for the input vcfs are stored in a json in the app home directory, would be better to use this to describe them all first and build a dict of vcf names -> file ids then just select from that.

we can use concurrent.futures too to make this speedy instead of sequential queries, this should do it:
```
import concurrent
import json
import dxpy

with open('job_input.json') as fh:
    input = json.load(fh)

# get just ids for the vcf input
ids = [x['$dnanexus_link'] for x in input['vcfs']]
ids_names = {}

with concurrent.futures.ThreadPoolExecutor(max_workers=len(ids)) as executor:
    # submit jobs mapping each id to describe call
    concurrent_jobs = {executor.submit(dxpy.describe, id): id for id in ids}
    for future in concurrent.futures.as_completed(concurrent_jobs):
        # access returned output as each is returned in any order
        try:
            response = future.result()
            ids_names[response['name']] = response['id']
        except Exception as exc:
            # catch any errors that might get raised during querying
            print(f"Error getting data for {concurrent_jobs[future]}: {exc}")
```

this will then give a dict of all vcf names as keys and file ids as values that you can look up from in the loop below, timing it is ~3 seconds for querying 48 sample ids



_Code quote:_
```Python
        # find dnanexus id
        vcf_object = dxpy.find_one_data_object(
            classname="file", name=vcf, project=args.dnanexus_project,
            more_ok=False
        )
```

**Review by Yu-jinKim — COMMENTED** [review]
Thanks, did not know about that input.json file

> *[Reviewable](https://reviewable.io/reviews/eastgenomics/opencga_data_upload/2#-:-NIHZ2D-9Q-qNZ02Z2YW:bhfp0a7)* status: 1 of 26 files reviewed, 6 unresolved discussions (waiting on @jethror1)

___
*[`dxapp.json` line 18 at r4](https://reviewable.io/reviews/eastgenomics/opencga_data_upload/2#-NIHGyJQEWZhK5k2VLuQ:-NIHZKQaCLkMojKv_fwb:b-896fix) ([raw file](https://github.com/eastgenomics/opencga_data_upload/blob/ce3f000c5a275fee55cbd9ca2626acca3ce0760b/dxapp.json#L18)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

files
</blockquote></details>

Done.
___
*[`resources/home/dnanexus/opencga_upload_and_index.py` line 96 at r4](https://reviewable.io/reviews/eastgenomics/opencga_data_upload/2#-NIHH32Z72NOTCrvlzHB:-NIHZW5E5etbdssKw0V5:b-896fix) ([raw file](https://github.com/eastgenomics/opencga_data_upload/blob/ce3f000c5a275fee55cbd9ca2626acca3ce0760b/resources/home/dnanexus/opencga_upload_and_index.py#L96)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

this can just be `if args.metadata:`
</blockquote></details>

Done.
___
*[`resources/home/dnanexus/opencga_upload_and_index.py` line 161 at r4](https://reviewable.io/reviews/eastgenomics/opencga_data_upload/2#-NIHLgcJ3Tl_vsi5GG5D:-NIHZXAlAeydgGZ57Ax7:b-896fix) ([raw file](https://github.com/eastgenomics/opencga_data_upload/blob/ce3f000c5a275fee55cbd9ca2626acca3ce0760b/resources/home/dnanexus/opencga_upload_and_index.py#L161)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

the file ID for the input vcfs are stored in a json in the app home directory, would be better to use this to describe them all first and build a dict of vcf names -> file ids then just select from that.

we can use concurrent.futures too to make this speedy instead of sequential queries, this should do it:
```
import concurrent
import json
import dxpy

with open('job_input.json') as fh:
    input = json.load(fh)

# get just ids for the vcf input
ids = [x['$dnanexus_link'] for x in input['vcfs']]
ids_names = {}

with concurrent.futures.ThreadPoolExecutor(max_workers=len(ids)) as executor:
    # submit jobs mapping each id to describe call
    concurrent_jobs = {executor.submit(dxpy.describe, id): id for id in ids}
    for future in concurrent.futures.as_completed(concurrent_jobs):
        # access returned output as each is returned in any order
        try:
            response = future.result()
            ids_names[response['name']] = response['id']
        except Exception as exc:
            # catch any errors that might get raised during querying
            print(f"Error getting data for {concurrent_jobs[future]}: {exc}")
```

this will then give a dict of all vcf names as keys and file ids as values that you can look up from in the loop below, timing it is ~3 seconds for querying 48 sample ids
</blockquote></details>

Done.

**Review by jethror1 — COMMENTED** [review]
> Reviewed 1 of 6 files at r1, 14 of 16 files at r3, 7 of 9 files at r4.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/opencga_data_upload/2)* status: 23 of 26 files reviewed, all discussions resolved

**Review by jethror1 — APPROVED** [review]
> Reviewed 1 of 1 files at r6, 2 of 2 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/opencga_data_upload/2)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Yu-jinKim)

**Comment by Yu-jinKim** [comment]
Closed as IVA is not longer being assessed

**Pull request closed without merging**
